### ISSUE TITLE
No module named 'fbx'

### ISSUE THREAD

**Issue by TheModdersDen** [MontagueM/HIME#4]
**Error:**
`ModuleNotFoundError: No module named 'fbx'`

**Version of Game:**
`6.10020.17500.0`

**Stack Trace/Error Log:**

> Traceback (most recent call last):
>   File "C:\Users\Username\HaloInfiniteModelExtractor\render_model_extractor.py", line 7, in <module>
>     import pyfbx
>   File "C:\Users\Username\HaloInfiniteModelExtractor\pyfbx.py", line 1, in <module>
>     import fbx
> ModuleNotFoundError: No module named 'fbx'

**Attempted Solutions:**

- Googling the error
- Installing pyfbx and py_fbx from pip
- Clearing the '__pycache__' folder

Any idea how to fix this?

Thanks in advance,
//TheModdersDen

**Comment by TheModdersDen** [comment]
Nevermind... Figured out what to do... Closing.

**Comment by CosmicDreamsOfCode** [comment]
> Nevermind... Figured out what to do... Closing.

What did you do?
I'm stuck on `ImportError: DLL load failed while importing fbx: The specified module could not be found.`
